name: Build in Production Environment

on:
    push:
        branches:
            - '**'
    pull_request:
        branches: [master]

jobs:
    validate-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: '10.33.4'

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '25.8.2'
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile --prod

            - name: Check for Quality Issues
              run: pnpm run chore:lint

            - name: Build Repository
              run: pnpm run build
